# These categories will be applied to all DAGs in the repo.
categories:
  - Airflow Fundamentals
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/callbacks_overview.py
  - path: dags/continuous_S3_dag.py
  - path: dags/deferrable_triggerdagrunoperator_toy.py
  - path: dags/json_yaml_macros_toy.py
  - path: dags/notifier_file_toy.py
  - path: dags/notifier_S3.py
  - path: dags/notifier_slack.py
  - path: dags/UI_features_toy.py